
spring:
  dubbo:
    application:
      name: dubbbo-client
    server: false
    registry:
      address: zookeeper://127.0.0.1:2181
    protocol:
      name: dubbo
      port: 20880
    scan: com.mt.client.service


server:
  port: 8091